# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget G4analysis G4digits_hits G4error_propagation G4event G4clhep G4zlib G4geometry G4global G4graphics_reps G4intercoms G4interfaces G4materials G4parmodels G4particles G4persistency G4physicslists G4processes G4readout G4run G4track G4tracking G4FR G4visHepRep G4RayTracer G4Tree G4VRML G4visXXX G4gl2ps G4GMocren G4vis_management G4modeling G4OpenGL)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target G4analysis
add_library(G4analysis SHARED IMPORTED)

set_target_properties(G4analysis PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4global;G4intercoms;G4zlib;/usr/lib/libexpat.so"
)

# Create imported target G4digits_hits
add_library(G4digits_hits SHARED IMPORTED)

set_target_properties(G4digits_hits PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4geometry;G4global;G4intercoms;G4materials;G4particles;G4track;G4graphics_reps"
)

# Create imported target G4error_propagation
add_library(G4error_propagation SHARED IMPORTED)

set_target_properties(G4error_propagation PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4event;G4geometry;G4global;G4intercoms;G4materials;G4particles;G4processes;G4run;G4track;G4tracking"
)

# Create imported target G4event
add_library(G4event SHARED IMPORTED)

set_target_properties(G4event PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track;G4tracking"
)

# Create imported target G4clhep
add_library(G4clhep SHARED IMPORTED)

set_target_properties(G4clhep PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
)

# Create imported target G4zlib
add_library(G4zlib SHARED IMPORTED)

set_target_properties(G4zlib PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
)

# Create imported target G4geometry
add_library(G4geometry SHARED IMPORTED)

set_target_properties(G4geometry PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4global;G4graphics_reps;G4intercoms;G4materials"
)

# Create imported target G4global
add_library(G4global SHARED IMPORTED)

set_target_properties(G4global PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4clhep"
)

# Create imported target G4graphics_reps
add_library(G4graphics_reps SHARED IMPORTED)

set_target_properties(G4graphics_reps PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4global;G4intercoms"
)

# Create imported target G4intercoms
add_library(G4intercoms SHARED IMPORTED)

set_target_properties(G4intercoms PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4global"
)

# Create imported target G4interfaces
add_library(G4interfaces SHARED IMPORTED)

set_target_properties(G4interfaces PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4global;G4intercoms;Qt5::Widgets;Qt5::Gui;Qt5::Core;Qt5::PrintSupport"
)

# Create imported target G4materials
add_library(G4materials SHARED IMPORTED)

set_target_properties(G4materials PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4global;G4intercoms"
)

# Create imported target G4parmodels
add_library(G4parmodels SHARED IMPORTED)

set_target_properties(G4parmodels PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track"
)

# Create imported target G4particles
add_library(G4particles SHARED IMPORTED)

set_target_properties(G4particles PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4global;G4materials;G4geometry;G4intercoms"
)

# Create imported target G4persistency
add_library(G4persistency SHARED IMPORTED)

set_target_properties(G4persistency PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4digits_hits;G4event;G4run;G4track;G4tracking"
)

# Create imported target G4physicslists
add_library(G4physicslists SHARED IMPORTED)

set_target_properties(G4physicslists PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4geometry;G4global;G4intercoms;G4materials;G4particles;G4processes;G4run;G4track;G4digits_hits;G4event;G4tracking"
)

# Create imported target G4processes
add_library(G4processes SHARED IMPORTED)

set_target_properties(G4processes PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4intercoms;G4materials;G4particles;G4track;G4analysis;/usr/lib/libexpat.so;G4zlib"
)

# Create imported target G4readout
add_library(G4readout SHARED IMPORTED)

set_target_properties(G4readout PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4event;G4geometry;G4global;G4intercoms;G4materials;G4particles;G4processes;G4run;G4track;G4tracking"
)

# Create imported target G4run
add_library(G4run SHARED IMPORTED)

set_target_properties(G4run PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track;G4tracking"
)

# Create imported target G4track
add_library(G4track SHARED IMPORTED)

set_target_properties(G4track PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4geometry;G4global;G4intercoms;G4materials;G4particles"
)

# Create imported target G4tracking
add_library(G4tracking SHARED IMPORTED)

set_target_properties(G4tracking PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track"
)

# Create imported target G4FR
add_library(G4FR SHARED IMPORTED)

set_target_properties(G4FR PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4modeling;G4vis_management"
)

# Create imported target G4visHepRep
add_library(G4visHepRep SHARED IMPORTED)

set_target_properties(G4visHepRep PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4tracking;G4vis_management;G4zlib"
)

# Create imported target G4RayTracer
add_library(G4RayTracer SHARED IMPORTED)

set_target_properties(G4RayTracer PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4particles;G4processes;G4track;G4tracking;G4vis_management"
)

# Create imported target G4Tree
add_library(G4Tree SHARED IMPORTED)

set_target_properties(G4Tree PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4particles;G4track;G4vis_management"
)

# Create imported target G4VRML
add_library(G4VRML SHARED IMPORTED)

set_target_properties(G4VRML PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4modeling;G4vis_management"
)

# Create imported target G4visXXX
add_library(G4visXXX SHARED IMPORTED)

set_target_properties(G4visXXX PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4modeling;G4tracking;G4vis_management"
)

# Create imported target G4gl2ps
add_library(G4gl2ps SHARED IMPORTED)

set_target_properties(G4gl2ps PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4zlib;/usr/lib/libGL.so;/usr/lib/libGLU.so"
)

# Create imported target G4GMocren
add_library(G4GMocren SHARED IMPORTED)

set_target_properties(G4GMocren PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4FR;G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4particles;G4tracking;G4vis_management"
)

# Create imported target G4vis_management
add_library(G4vis_management SHARED IMPORTED)

set_target_properties(G4vis_management PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4particles;G4processes;G4run;G4track;G4tracking"
)

# Create imported target G4modeling
add_library(G4modeling SHARED IMPORTED)

set_target_properties(G4modeling PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4run;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track;G4tracking"
)

# Create imported target G4OpenGL
add_library(G4OpenGL SHARED IMPORTED)

set_target_properties(G4OpenGL PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_auto_type;cxx_delegating_constructors;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_final;cxx_lambdas;cxx_nullptr;cxx_override;cxx_range_for;cxx_strong_enums;cxx_uniform_initialization"
  INTERFACE_LINK_LIBRARIES "G4digits_hits;G4event;G4run;G4particles;G4processes;G4track;G4materials;G4geometry;G4gl2ps;G4global;G4graphics_reps;G4intercoms;G4interfaces;G4modeling;G4tracking;G4vis_management;/usr/lib/libGL.so;/usr/lib/libGLU.so;/usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libXmu.so;Qt5::OpenGL;Qt5::Gui;Qt5::PrintSupport;Qt5::Widgets"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/Geant4LibraryDepends-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
